In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y=iris.target

In [6]:
from sklearn.neural_network import MLPClassifier
X_train,X_test,y_train,y_test = train_test_split(x,y)

In [9]:
clf = MLPClassifier(hidden_layer_sizes=(20,10,),max_iter=3000)
clf.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(20, 10), max_iter=3000)

In [10]:
clf.score(X_test,y_test)

0.9736842105263158

In [16]:
clf.intercepts_[1].shape

(10,)

In [19]:
import numpy as np
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y= np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [46]:
def sig(z):
  return 1/(1+np.exp(-z))


In [45]:
def derivativeSig(z):
  return sig(z)*(1-sig(z))

In [56]:
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights,bias

(array([[ 0.82951965],
        [-0.32234663]]),
 array([-0.30774249]))

In [63]:
output0 = X
output = sig(np.dot(output0,weights)+bias)
lr=0.1
output

array([[0.00717223],
       [0.18697493],
       [0.07557986],
       [0.7224359 ]])

In [66]:
for _ in range(10000):
  first_term = output-Y
  input_for_last_layer = np.dot(output0,weights)+bias
  second_term=derivativeSig(input_for_last_layer)
  first_two = first_term * second_term
  first_two
  changes = np.array([[0.0],[0.0]])
  for i in range(2):
    for j in range(4):
      changes[i][0]+=first_two[j][0]*output0[j][i]
  weights = weights - lr*changes
  bias_change=0.0
  for j in range(4):
    bias_change+=first_two[j][0]*1
  bias = bias - lr*bias_change


In [68]:
for _ in range(10000):
  first_term = output-Y
  input_for_last_layer = np.dot(output0,weights)+bias
  second_term=derivativeSig(input_for_last_layer)
  first_two = first_term * second_term
  first_two
  changes = np.dot(output0.T,first_two)
  weights = weights - lr*changes
  bias_change=np.sum(first_two)
  bias = bias - lr*bias_change

In [69]:
output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[7.00697563],
        [7.55853348]]),
 array([-11.40205407]),
 array([[1.11723873e-05],
        [2.09689499e-02],
        [1.21875437e-02],
        [9.59435627e-01]]))

In [28]:
wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1

In [29]:
 output0 = X
 outputHidden = sig(np.dot(output0,wh)+bh)

In [31]:
outputHidden.shape
output = sig(np.dot(outputHidden,wo)+bo)
output

array([[0.55941485],
       [0.60793442],
       [0.53136717],
       [0.58168219]])